// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ayah struct {
	ID                  int32       `json:"id"`
	SurahID             int32       `json:"surah_id"`
	AyahNumber          int32       `json:"ayah_number"`
	TextArabic          string      `json:"text_arabic"`
	TextUthmani         pgtype.Text `json:"text_uthmani"`
	TextTransliteration pgtype.Text `json:"text_transliteration"`
	Juz                 int32       `json:"juz"`
	Hizb                int32       `json:"hizb"`
	Rub                 int32       `json:"rub"`
	Page                int32       `json:"page"`
	Sajdah              pgtype.Text `json:"sajdah"`
}

type AyahAudio struct {
	ID         string      `json:"id"`
	AyahID     int32       `json:"ayah_id"`
	ReciterID  string      `json:"reciter_id"`
	AudioUrl   string      `json:"audio_url"`
	DurationMs pgtype.Int4 `json:"duration_ms"`
}

type AyahTranslation struct {
	ID            string `json:"id"`
	AyahID        int32  `json:"ayah_id"`
	TranslationID string `json:"translation_id"`
	Text          string `json:"text"`
}

type Bookmark struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	AyahID       int32              `json:"ayah_id"`
	CollectionID pgtype.Text        `json:"collection_id"`
	Color        pgtype.Text        `json:"color"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Version      int32              `json:"version"`
	DeviceID     pgtype.Text        `json:"device_id"`
	OperationID  pgtype.Text        `json:"operation_id"`
}

type Collection struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Version     int32              `json:"version"`
	DeviceID    pgtype.Text        `json:"device_id"`
	OperationID pgtype.Text        `json:"operation_id"`
}

type KhatmPlan struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	TargetDate       pgtype.Timestamptz `json:"target_date"`
	DailyTargetPages pgtype.Int4        `json:"daily_target_pages"`
	CompletedPages   int32              `json:"completed_pages"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Version          int32              `json:"version"`
	DeviceID         pgtype.Text        `json:"device_id"`
	OperationID      pgtype.Text        `json:"operation_id"`
}

type Note struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	AyahID      int32              `json:"ayah_id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Version     int32              `json:"version"`
	DeviceID    pgtype.Text        `json:"device_id"`
	OperationID pgtype.Text        `json:"operation_id"`
}

type ReadingHistory struct {
	ID     string             `json:"id"`
	UserID string             `json:"user_id"`
	AyahID int32              `json:"ayah_id"`
	ReadAt pgtype.Timestamptz `json:"read_at"`
}

type ReadingProgress struct {
	UserID      string             `json:"user_id"`
	LastSurahID pgtype.Int4        `json:"last_surah_id"`
	LastAyahID  pgtype.Int4        `json:"last_ayah_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Version     int32              `json:"version"`
	DeviceID    pgtype.Text        `json:"device_id"`
	OperationID pgtype.Text        `json:"operation_id"`
}

type Reciter struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Style pgtype.Text `json:"style"`
}

type Surah struct {
	ID                  int32       `json:"id"`
	NameArabic          string      `json:"name_arabic"`
	NameTransliteration string      `json:"name_transliteration"`
	NameTranslation     string      `json:"name_translation"`
	RevelationPlace     string      `json:"revelation_place"`
	AyahCount           int32       `json:"ayah_count"`
	OrderInRevelation   pgtype.Int4 `json:"order_in_revelation"`
}

type Translation struct {
	ID         string      `json:"id"`
	Language   string      `json:"language"`
	Name       string      `json:"name"`
	Translator pgtype.Text `json:"translator"`
	Source     pgtype.Text `json:"source"`
}

type User struct {
	ID            string             `json:"id"`
	Email         pgtype.Text        `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	DisplayName   pgtype.Text        `json:"display_name"`
	AuthProvider  string             `json:"auth_provider"`
	IsAnonymous   bool               `json:"is_anonymous"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserDevice struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Platform   string             `json:"platform"`
	PushToken  pgtype.Text        `json:"push_token"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UserPreference struct {
	UserID               string             `json:"user_id"`
	Language             string             `json:"language"`
	TranslationID        pgtype.Text        `json:"translation_id"`
	ReciterID            pgtype.Text        `json:"reciter_id"`
	CalculationMethod    pgtype.Text        `json:"calculation_method"`
	Madhhab              pgtype.Text        `json:"madhhab"`
	Latitude             pgtype.Float8      `json:"latitude"`
	Longitude            pgtype.Float8      `json:"longitude"`
	Timezone             pgtype.Text        `json:"timezone"`
	Theme                string             `json:"theme"`
	FontSize             string             `json:"font_size"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	DeviceID  pgtype.Text        `json:"device_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserSetting struct {
	UserID           string             `json:"user_id"`
	SyncEnabled      bool               `json:"sync_enabled"`
	AnalyticsEnabled bool               `json:"analytics_enabled"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
