// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetAyah(ctx context.Context, id int32) (Ayah, error)
	GetSurah(ctx context.Context, id int32) (Surah, error)
	ListAudioForAyah(ctx context.Context, ayahID int32) ([]AyahAudio, error)
	ListAyahsBySurah(ctx context.Context, surahID int32) ([]Ayah, error)
	ListReciters(ctx context.Context) ([]Reciter, error)
	ListSurahs(ctx context.Context) ([]Surah, error)
	ListTranslations(ctx context.Context) ([]Translation, error)
	ListTranslationsForAyah(ctx context.Context, ayahID int32) ([]ListTranslationsForAyahRow, error)
	SearchAyahs(ctx context.Context, arg SearchAyahsParams) ([]Ayah, error)
}

var _ Querier = (*Queries)(nil)
