// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quran.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAyah = `-- name: GetAyah :one
SELECT id, surah_id, ayah_number, text_arabic, text_uthmani, text_transliteration, juz, hizb, rub, page, sajdah FROM ayahs WHERE id = $1
`

func (q *Queries) GetAyah(ctx context.Context, id int32) (Ayah, error) {
	row := q.db.QueryRow(ctx, getAyah, id)
	var i Ayah
	err := row.Scan(
		&i.ID,
		&i.SurahID,
		&i.AyahNumber,
		&i.TextArabic,
		&i.TextUthmani,
		&i.TextTransliteration,
		&i.Juz,
		&i.Hizb,
		&i.Rub,
		&i.Page,
		&i.Sajdah,
	)
	return i, err
}

const getSurah = `-- name: GetSurah :one
SELECT id, name_arabic, name_transliteration, name_translation, revelation_place, ayah_count, order_in_revelation FROM surahs WHERE id = $1
`

func (q *Queries) GetSurah(ctx context.Context, id int32) (Surah, error) {
	row := q.db.QueryRow(ctx, getSurah, id)
	var i Surah
	err := row.Scan(
		&i.ID,
		&i.NameArabic,
		&i.NameTransliteration,
		&i.NameTranslation,
		&i.RevelationPlace,
		&i.AyahCount,
		&i.OrderInRevelation,
	)
	return i, err
}

const listAudioForAyah = `-- name: ListAudioForAyah :many
SELECT id, ayah_id, reciter_id, audio_url, duration_ms FROM ayah_audio WHERE ayah_id = $1
`

func (q *Queries) ListAudioForAyah(ctx context.Context, ayahID int32) ([]AyahAudio, error) {
	rows, err := q.db.Query(ctx, listAudioForAyah, ayahID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AyahAudio{}
	for rows.Next() {
		var i AyahAudio
		if err := rows.Scan(
			&i.ID,
			&i.AyahID,
			&i.ReciterID,
			&i.AudioUrl,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAyahsBySurah = `-- name: ListAyahsBySurah :many
SELECT id, surah_id, ayah_number, text_arabic, text_uthmani, text_transliteration, juz, hizb, rub, page, sajdah FROM ayahs WHERE surah_id = $1 ORDER BY ayah_number
`

func (q *Queries) ListAyahsBySurah(ctx context.Context, surahID int32) ([]Ayah, error) {
	rows, err := q.db.Query(ctx, listAyahsBySurah, surahID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ayah{}
	for rows.Next() {
		var i Ayah
		if err := rows.Scan(
			&i.ID,
			&i.SurahID,
			&i.AyahNumber,
			&i.TextArabic,
			&i.TextUthmani,
			&i.TextTransliteration,
			&i.Juz,
			&i.Hizb,
			&i.Rub,
			&i.Page,
			&i.Sajdah,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReciters = `-- name: ListReciters :many
SELECT id, name, style FROM reciters ORDER BY name
`

func (q *Queries) ListReciters(ctx context.Context) ([]Reciter, error) {
	rows, err := q.db.Query(ctx, listReciters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reciter{}
	for rows.Next() {
		var i Reciter
		if err := rows.Scan(&i.ID, &i.Name, &i.Style); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurahs = `-- name: ListSurahs :many
SELECT id, name_arabic, name_transliteration, name_translation, revelation_place, ayah_count, order_in_revelation FROM surahs ORDER BY id
`

func (q *Queries) ListSurahs(ctx context.Context) ([]Surah, error) {
	rows, err := q.db.Query(ctx, listSurahs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Surah{}
	for rows.Next() {
		var i Surah
		if err := rows.Scan(
			&i.ID,
			&i.NameArabic,
			&i.NameTransliteration,
			&i.NameTranslation,
			&i.RevelationPlace,
			&i.AyahCount,
			&i.OrderInRevelation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslations = `-- name: ListTranslations :many
SELECT id, language, name, translator, source FROM translations ORDER BY language, name
`

func (q *Queries) ListTranslations(ctx context.Context) ([]Translation, error) {
	rows, err := q.db.Query(ctx, listTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Translation{}
	for rows.Next() {
		var i Translation
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Name,
			&i.Translator,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsForAyah = `-- name: ListTranslationsForAyah :many
SELECT
    ayah_translations.id,
    ayah_translations.ayah_id,
    ayah_translations.translation_id,
    ayah_translations.text,
    translations.language,
    translations.name AS translation_name,
    translations.translator
FROM ayah_translations
JOIN translations ON translations.id = ayah_translations.translation_id
WHERE ayah_translations.ayah_id = $1
`

type ListTranslationsForAyahRow struct {
	ID              string      `json:"id"`
	AyahID          int32       `json:"ayah_id"`
	TranslationID   string      `json:"translation_id"`
	Text            string      `json:"text"`
	Language        string      `json:"language"`
	TranslationName string      `json:"translation_name"`
	Translator      pgtype.Text `json:"translator"`
}

func (q *Queries) ListTranslationsForAyah(ctx context.Context, ayahID int32) ([]ListTranslationsForAyahRow, error) {
	rows, err := q.db.Query(ctx, listTranslationsForAyah, ayahID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranslationsForAyahRow{}
	for rows.Next() {
		var i ListTranslationsForAyahRow
		if err := rows.Scan(
			&i.ID,
			&i.AyahID,
			&i.TranslationID,
			&i.Text,
			&i.Language,
			&i.TranslationName,
			&i.Translator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAyahs = `-- name: SearchAyahs :many
SELECT ayahs.id, ayahs.surah_id, ayahs.ayah_number, ayahs.text_arabic, ayahs.text_uthmani, ayahs.text_transliteration, ayahs.juz, ayahs.hizb, ayahs.rub, ayahs.page, ayahs.sajdah
FROM ayahs
WHERE ayahs.text_arabic ILIKE '%' || $1::text || '%'
   OR ayahs.text_transliteration ILIKE '%' || $1::text || '%'
ORDER BY ayahs.id
LIMIT $3::int
OFFSET $2::int
`

type SearchAyahsParams struct {
	Query     string `json:"query"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) SearchAyahs(ctx context.Context, arg SearchAyahsParams) ([]Ayah, error) {
	rows, err := q.db.Query(ctx, searchAyahs, arg.Query, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ayah{}
	for rows.Next() {
		var i Ayah
		if err := rows.Scan(
			&i.ID,
			&i.SurahID,
			&i.AyahNumber,
			&i.TextArabic,
			&i.TextUthmani,
			&i.TextTransliteration,
			&i.Juz,
			&i.Hizb,
			&i.Rub,
			&i.Page,
			&i.Sajdah,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
